doctrine:
  dbparams:
    driver: "pdo_mysql"
    user: "dbuser"
    password: "s3cr3t"
    dbname: "db01"
    host: "localhost"
apache:
  group: "nobody"
  service: "/etc/init.d/apache2"
  reload: ["graceful"]
  restart: ["restart"]
  anonip: "/path/to/anonip.py"
php:
  service: "/etc/init.d/php-fpm-php%s"
  reload: ["restart"]
  restart: ["restart"]
certbot:
  service: "/usr/bin/certbot"
  challenge: "/www/htdocs/letsencrypt"
  reload: ["certonly"]
  restart: ["certonly"]
general:
  locale: de_DE
  group: account
  basedir: "/var/www/localhost/accounts"
  fpmdir: "/run/php-fpm"
  certdir: "/etc/letsencrypt/live"
  certemail: "cert@example.com"
