doctrine:
  dbparams:
    driver: "pdo_mysql"
    user: "dbuser"
    password: "s3cr3t"
    dbname: "db01"
    host: "localhost"
apache:
  group: "nobody"
general:
  locale: de_DE
  group: account
  basedir: "/var/www/localhost/accounts"
  fpmdir: "/var/run/php-fpm"
  certdir: "/etc/letsencrypt/live"
  certemail: "info@tollwerk.de"
