doctrine:
  dbparams:
    driver: "pdo_mysql"
    user: "dbuser"
    password: "s3cr3t"
    dbname: "db01"
    host: "localhost"
apache:
  group: "nobody"
  reload: "/etc/init.d/apache2 graceful"
php:
  service: "/etc/init.d/php-fpm-php%s"
  reload: ["restart"]
  restart: ["restart"]
general:
  locale: de_DE
  group: account
  basedir: "/var/www/localhost/accounts"
  fpmdir: "/var/run/php-fpm"
  certdir: "/etc/letsencrypt/live"
  certemail: "info@tollwerk.de"
